In [1]:

import numpy as np
import pandas as pd


## Part 1 - Numpy

In [2]:

# Define custom arrays
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

# Stack vertically
vertical_stack = np.vstack((A, B))

# Stack horizontally
horizontal_stack = np.hstack((A, B))

print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)


Vertical Stack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontal Stack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [3]:

common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)


Common Elements: []


In [4]:

filtered_A = A[(A >= 5) & (A <= 10)]
print("Numbers in A between 5 and 10:", filtered_A)


Numbers in A between 5 and 10: [5 6]


In [5]:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Rows:\n", filtered_rows)


Filtered Rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


## Part 2 - Pandas

In [6]:

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_df)


   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [7]:

df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df[['Min.Price', 'Max.Price']].isnull().sum())  # Verify no missing values


Min.Price    0
Max.Price    0
dtype: int64


In [8]:

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Find rows where sum > 100
filtered_rows = df[df.sum(axis=1) > 100]
print("Rows where row sum > 100:\n", filtered_rows)


Rows where row sum > 100:
      0   1   2   3
0   26  29  22  36
5   29  28  22  37
7   25  37  38  26
9   15  25  36  36
10  16  32  36  30
11  16  37  35  16
13  20  39  31  36
14  25  26  31  22
